---
title: "Real Data"
author: "J"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(dplyr)
library(purrr)
```

```{r}
toolik_biochem <- read.csv(here::here("data", "2011_Kling_Akchem.csv"))
# view(toolik_biochem)

toolik_biochem <- toolik_biochem %>% clean_names()
# toolik_biochem

# names(toolik_biochem)
inlet_biochem <- toolik_biochem %>%
  select(p_h, doc_u_m, tdn_u_m)
# inlet_biochem

mean_values <- vector(mode = "numeric", length = ncol(inlet_biochem))

for (i in seq_along(inlet_biochem)) {
  
  mean_values[i] <- mean(as.numeric(inlet_biochem[[i]]), na.rm = TRUE)
  
}

names(mean_values) <- names(inlet_biochem)
mean_values

inlet_biochem$p_h <- as.numeric(inlet_biochem$p_h)     
inlet_biochem$doc_u_m <- as.numeric(inlet_biochem$doc_u_m)
inlet_biochem$tdn_u_m <- as.numeric(inlet_biochem$tdn_u_m)


map_df(.x = inlet_biochem, .f = mean, na.rm = TRUE)

apply(X = inlet_biochem, MARGIN = 2, FUN = mean, na.rm = TRUE)
mean_values
```
